---

- hosts: all
  become: true
  tasks:

  - name: update repo index
    apt:
      update_cache: yes 
    when: ansible_distribution == "Debian"
         
  - name: install the apache2 & lib apache package
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"
